### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by cherrynoize** [jtsiomb/xlivebg#15]
I get this error trying to install with `yay` on Arch:

```
vid.c:72:41: error: ‘AVStream’ has no member named ‘codec’
   72 |                 if(vf->avctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
      |                                         ^~
vid.c:82:51: error: ‘AVStream’ has no member named ‘codec’
   82 |         vf->cctx = vf->avctx->streams[vf->vstream]->codec;
```

This seems to be an issue with the `video` subpackage. What should I do about this?

Also, for context, everything else seems to work (I can run `xlivebg` and `xlivebg-gui`, though the latter will complain about the lack of plugins).

**Comment by jtsiomb** [comment]
ffmpeg changes its API every week, and the video plugin as was written is no longer compatible with current versions of ffmpeg. Just disable it by passing `--disable-plugin-video` to `configure`. For this reason the video plugin has been dropped since the original release.

As for the lack of plugins, make sure to run `make install-all` after compiling. `make install` will only install the main daemon, not the plugins or the config gui.
