### ISSUE TITLE
compton and conky

### ISSUE THREAD

**Issue by elig0n** [jtsiomb/xlivebg#6]
Thanks for creating this.
When I run xlivebg with conky running conky is not shown.
If I run compton (picom) then xlivebg display disappear altogether.

**Comment by jtsiomb** [comment]
Compton is a compositor right? I did try running xlivebg under standalone compositors (I tried xcompmgr), and the compositor was not playing nicely with xlivebg drawing on the root window. The solution was to run xlivebg with the `-n` argument, to make it create its own "desktop" window. Other compositors didn't have a problem with the default drawing mode, so I'm not sure if that's your problem, but please try the `-n` argument and let me know if the problem persists.

As for conky, I will have to install it and see, but I've been running xosview with xlivebg without any issues. Is by any chance conky also trying to draw to the desktop window instead of creating its own? Maybe it has an option to create a regular window instead of doing that?

**Comment by elig0n** [comment]
er, I meant to say that conky is shown but transparency doesn't work

**Comment by jtsiomb** [comment]
This is probably better asked to the conky developers which are going to be familiar with how it handles transparency. If it just snaps a shot of the desktop before it starts, and uses it as a backdrop for its window, it's obviously not going to work with xlivebg which continuously updates what's shown in the desktop.

The only way for conky to be able to show the live wallpaper behind it, is if it creates a window with an alpha channel, and you're running a compositor to correctly composite the alpha-masked contents of conky over the xlivebg desktop window.

For instance I'm pretty sure that if you try to run this https://github.com/jtsiomb/alphaclock which creates a window and OpenGL context with an RGBA visual, it should be composited correctly with alpha blending over xlivebg (if you also have a compositor running).

If your compton issue was solved by my previous suggestion, please let me know so that I can close this bug report.

**Comment by elig0n** [comment]
In conky I have `own_window_argb_value` and `own_window_type = 'override' set. Running conky in window mode and moving it around shows that the underlying desktop gets redrawn accordingly with every movement so it's "live".
Running `compton` doesn't make conky overlay xlivebg. Running `xcompmgr` makes xlivebg "take over" the display with windows and other window manager stuff (including conky) being invisible mostly and blinking when mouse is moved.
I had no success compiling alphaclock and its dependencies.
Running xlivebg with `-n` and `compton` first and then `xcompmgr` still did not help conky appear "above" xlivebg animation, but the blinking issue I described disappeared when xlivebg ran in window mode.

**Comment by jtsiomb** [comment]
Compton and xcompmgr are both compositors, running both of them at once is not going to work.

I cannot help you with conky. You need to refer to its documentation, or failing that, ask conky's developers about how it handles transparency and RGBA visuals.

Since your message implies that, conky transparency aside, xlivebg works with your compositor with `-n`, I'm closing this bug report. Let me know if I misunderstood, or I missed something that is potentially a bug in xlivebg and I can help with.
